services:
     - type: web
       name: mapa-vida
       env: static
       buildCommand: npm install && npm run build
       staticPublishPath: ./dist
       headers:
         - path: /*
           name: Cache-Control
           value: no-cache